const DescriptionConst = {

    SUCCESS: "Success",
    FAILED: "Failed",
    VALIDATION: "Validation failed",
    DUPLICATION: "Duplication",
    NOTFOUND: "Not found",
    FORBIDDEN: "Forbidden",
    NO_CHANGE: "No change",
    BAD_REQ: "Bad request",
    AUTHENTICATION_FAILED: "Authentication Failed.",
    AUTHORIZATION_FAILED:"Authorization Failed.",
    LOGOUT:"SUCCESSULLY LOGOUT",
    SETTING_LOADED:"All Setting Loaded Success",
    
    EMAIL_INVALID: "Your Email is invalid : ",
    EMAIL_NOT_SEND: "Email is not send due to some issues.",
    EMAIL_SEND: "Email is sent successfully.",
    INPUT_INVALID: "Your input is invalid like no null or undefined values are considered. ",
    USER_LOGOUT: "User had been Logout.",
    USER_LOGIN: "Login Successful: Welcome Back to our Website!",
    USER_SIGNIN: "Login Successful: Welcome Back to our Website!",
    USER_ALREADY_LOGOUT: "User had been already logout.",
    ZIPCODE_INVALID: "Your Zipcode is invalid : ",
    GENDER_INVALID: "Your Gender is invalid : ",
    STATUS_INVALID: "Your Status is invalid : ",
    ROLE_INVALID: "Your Role is invalid : ",
    FNAME_INVALID: "Your first name is invalid : ",
    MNAME_INVALID: "Your middle name is invalid : ",
    LNAME_INVALID: "Your last name is invalid : ",
    CITY_INVALID: "Your city name is invalid : ",
    STATE_INVALID: "Your state name is invalid : ",
    AGE_INVALID: "Your age is invalid : ",
    DATE_INVALID: "Your date's format is invalid and must be in this YYYY-MM-DD  : ",
    FUTURE_DATE_INVALID: "Your date is from future : ",
    PASSWORD_INVALID : "Your password is not strong.",
    PASSWORD_EMPTY : "Password field is empty or undefined.",
    NUMBER_INVALID: "Your mobile number is invalid : ",
    RECORD_ADDED: "Record added successfully",
    ALREADY_EXIST: "Already Exist record",
    BULK_BODY: "Request body must be an array of objects",
    NOT_F: "User is not found",
    NO_CHANGE: "No changes detected,Update not required.",
    NOT_ACTIVE: "User status is not Active",
    UPDATE_RECORD: "Record updated successfully",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    DELETE_RECORD: "Record deleted successfully",
    FILTER_RECORD: "Successfully, Filtered records.",
    ENTER_FILTER: "Please enter at least one filter criteria",
    GET_RECORD: "Successfully, get all the records",
    BAD_REQUEST: "Something Wrong from UserSide input",
    AUTHENTICATION_FAILED_MSG: "You have entered wrong password",
    AUTHORIZATION_FAILED_MSG: "ACCESS IS DENIED",
    YOU_HAVE_REMAINING : " Invalid password & Remaining attempts are :  ",
    ACCESS_DENIED: "Access is denied",
    TOKEN_IS_NOT : "Token is not provided",
    USER_IS_NOT_FOUND: "UserSession is not detected",
    JWT_AUTH_FAILED: "JWT authentication failed",
    TOKEN_IS_EXPIRED: "Token is expired",
    TOKEN_SUCCESS: "Successful login, Token is generated",
    OTP_GENERATED:"OTP Successfully generated and send to your email",
    OTP_INVALID: "Your entered OTP is incorrect, please retry with new OTP.",
    OTP_EXPIRE: "Your entered OTP has been expired, please retry with new OTP.",
    USER_IS_UNBLOCKED: "User is been unblock.",
    USER_IS_BLOCK: "You have been blocked due to many invalid attempts.",
    BLOCKED_ACCOUNT: "Your account has been temporarily blocked due to multiple failed login attempts. Please try again in 10 minutes.",

    OTP_NOT_PROVIDED:"OTP NOT PROVIDED",
    INVALID_ARRAY_FORMATE:"Provide data in array [ {user1} , {user2} ]",
    NO_HEADER_PROVIDED:"HEADER IS NOT PROVIDED",
    NO_TOKEN_PROVIDED:"TOKEN IS NOT PROVIDED",

    firstName_INVALID:"firstName is Invalid",   
    middleName_INVALID:"middleName is Invalid",    
    lastName_INVALID:"lastName is Invalid",    
    email_INVALID:"email is Invalid",
    password_INVALID:"password is Invalid",
    gender_INVALID:"gender is Invalid",
    dob_INVALID:"dateOfBirth is Invalid",
    city_INVALID:"city is Invalid",
    state_INVALID:"state is Invalid",
    zipcode_INVALID:"zipcode is Invalid",
    mobilenumber_INVALID:"mobileNumber is Invalid", 
    
    firstName_UNDEFINED:"firstName is undefined",
    middleName_UNDEFINED:"middleName is undefined",
    lastName_UNDEFINED:"lastName is undefined",
    email_UNDEFINED:"email is undefined",
    password_UNDEFINED:"password is undefined",
    gender_UNDEFINED:"gender is undefined",
    dob_UNDEFINED:"dateOfBirth is undefined",
    city_UNDEFINED:"city is undefined",
    state_UNDEFINED:"state is undefined",
    zipcode_UNDEFINED:"zipcode is undefined",
    mobileNumber_UNDEFINED:"mobileNumber is undefined",



    CATEGORIE_ADDED_SUCCESS:"Food Categorie Inserted Successfully",
    FOODITEM_ADDED_SUCCESS:"Food Item Inserted Sucessfully",
    IMAGE_NOT_PROVIDED:"Please Provide Image",
    ADDON_ADDED_SUCCESS:"Addon Inserted Successfully",

    RECORD_NOT_FOUND:"RECORD NOT FPUND",
    ALREADY_SUBSCRIBED:"THIS EMAIL IS ALREADY SUBSCRIBED TO THE NEWSLETTER",
    VERIFICATION_EMAIL_SEND:"THE VERIFICATION EMAIL IS SEND TO YOUR EMAIL PLEASE CHECK WITHIN 24 HOURS",
    EMAIL_VERIFIED_SUCCESS:"YOUR EMAIL IS SUCCESSFULLY VERIFIED",
    ALREADY_VERIFIED_TOKEN:"ALREADY VERIFIED TOKEN",
};



export {DescriptionConst};